model:
  type: cheb_conv
  name: ChebEEGNet
  params:
    in_channels: 12
    hidden_channels: 32
    out_channels: 1
    pooling_type: sum 
    K: 1
batch_size: 32
learning_rate: 0.001
weight_decay: 0
epochs: 200
seed: 42
oversampling_power: 0.6

embeddings: False
selected_features:  True
edge_strategy: correlation
top_k :  5
correlation_threshold: False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
