model:
  type: encoder_gnn
  name: GNN_Encoder
  encoder:
    type: cnn_bilstm
    name: EEGConvBiLSTM
    params:
      output_dim_lstm: 64
  gnn:
    type: gat
    name: EEGGAT
    params:
       in_channels: 64
  
batch_size: 8
learning_rate: 0.01
weight_decay: 0
epochs: 200
seed: 42
oversampling_power: 1

embeddings: False
selected_features: False
edge_strategy: correlation
top_k : 5
correlation_threshold: False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50