model:
  type: encoder_gnn
  name: GNN_Encoder
  encoder:
    type: cnn_bilstm
    name: EEGConvBiLSTM
    params:
      output_dim_lstm: 64
  gnn:
    type: gcn
    name: EEGGCN
    params:
      hidden_channels: 64
      out_channels: 32
      num_conv_layers: 2
      pooling_type: mean
      dropout_prob: 0.5
      in_channels: 64
  
batch_size: 32
learning_rate: 0.01
weight_decay: 0.01
epochs: 200
seed: 42
oversampling_power: 1

embeddings: False
selected_features: False
edge_strategy: correlation
top_k : False
correlation_threshold: 0.7
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50