model:
  type: encoder_gnn
  name: GNN_Encoder
  encoder:
    type: cnn
    name: EEG1DCNNEncoder
    params:
      out_dim: 128
  gnn:
    type: mpnn
    name: EEGMPNN
    params:
      in_channels: 128
      hidden_channels: 64
      out_channels: 1
      num_mp_layers: 2
      pooling_message: mean
      pooling_type: mean
      dropout_prob: 0
  
batch_size: 32
learning_rate: 0.01
weight_decay: 0.01
epochs: 200
seed: 42
oversampling_power: 1

selected_features: False
edge_strategy: correlation
top_k : False
correlation_threshold: 0.7
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
