model:
  type: cnnbilstm
  name: CNNLSTM
  params:   
    bidirectional: True   
    dropout: 0.3   
    lstm_hidden_size: 64

batch_size: 32
learning_rate: 0.001
weight_decay: 0.0001
epochs: 200
seed: 42
oversampling_power: 0.7

embeddings: False
selected_features:  False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
apply_rereferencing: False
apply_normalization: True
