model:
  type: cnnlstm_embeddings
  name: CNNLSTMEmb
  params:
    embedding_dim: 128             

batch_size: 32
learning_rate: 0.001
weight_decay: 0
epochs: 200
seed: 42
oversampling_power: 1

selected_features: False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
apply_rereferencing: False
apply_normalization: True