model:
  type: gcn
  name: EEGGCN
  params:
    hidden_channels: 64
    out_channels: 1
    num_conv_layers: 3
    pooling_type: mean

batch_size: 32
learning_rate: 0.001
epochs: 200
seed: 42
oversampling_power: 0.5

edge_strategy: spatial
correlation_threshold: 0.7
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
