model:
  type: graphconvnet_mini
  name: EEGGraphConvNetMini
  params:
     in_channels: 60
     dropout: 0.5

batch_size: 64
learning_rate: 0.001
weight_decay: 0.001
epochs: 200
seed: 42
oversampling_power: 0.5

embeddings: False
selected_features:  True
edge_strategy: correlation
top_k :  2
correlation_threshold: False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
