model:
  type: graphconvnet_mini
  name: EEGGraphConvNetMini
  params:
     in_channels: 5

batch_size: 64
learning_rate: 0.0001
weight_decay: 0.0001
epochs: 200
seed: 42
oversampling_power: 0.6

embeddings: False
selected_features:  True
edge_strategy: correlation
top_k :  19
correlation_threshold: False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
