model:
  type: lstm_graphconv 
  name: EEGGraphConvLSTMNet
  params:
     in_channels: 3000

batch_size: 16
learning_rate: 0.001
weight_decay: 0.001
epochs: 200
seed: 42
oversampling_power: 0.5

embeddings: False
selected_features:  False
edge_strategy: correlation
top_k :  19
correlation_threshold: False
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
