model:
  type: mlp_no_graph
  name: EEGBaselineMLP
  params:
    dropout: 0.3
    input_dim: 1140

batch_size: 64
learning_rate: 0.001
weight_decay: 0.0001
epochs: 200
seed: 42
oversampling_power: 0.8

embeddings: False
selected_features: True
low_bandpass_frequency: 0.5
high_bandpass_frequency: 50
apply_rereferencing: False
apply_normalization: True